params:
  cuda_devices: []

optional_plugin_components: {}

shard_descriptor:
  template: histology_shard_descriptor.HistologyShardDescriptor
  params:
    data_folder: histology_data
    rank_worldsize: 1,2
