name: Ubuntu (latest)

on:
  schedule:
    - cron: '0 0 * * *'

permissions:
  contents: read

jobs:
  lint: # from lint.yml
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.8
      uses: actions/setup-python@v3
      with:
        python-version: "3.8"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements-linters.txt 
        pip install .
    - name: Lint with flake8
      run: |
        flake8 --show-source

  pytest-coverage: # from pytest_coverage.yml
    needs: lint
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.8
      uses: actions/setup-python@v3
      with:
        python-version: "3.8"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest coverage
        pip install -r requirements-test.txt
        pip install .
    - name: Test with pytest and report code coverage
      run: |
        coverage run -m pytest -rA
        coverage report
    
  dockerization: # from dockerization.yml
    needs: [lint, pytest-coverage]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.8
        uses: actions/setup-python@v3
        with:
          python-version: "3.8"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .
      - name: Dockerization test
        run: |
          python -m tests.github.dockerization_test
  
  interactive-kvasir: # from interactive-kvasir.yml
    needs: [lint, pytest-coverage, dockerization]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.8
      uses: actions/setup-python@v3
      with:
        python-version: "3.8"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install .
    - name: Interactive API - pytorch_kvasir_unet
      run: |
        python setup.py build_grpc
        pip install torch==1.13.1
        pip install torchvision==0.14.1
        python -m tests.github.interactive_api_director.experiments.pytorch_kvasir_unet.run
  
  cli:
    needs: [lint, pytest-coverage, dockerization, interactive-kvasir]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.8
        uses: actions/setup-python@v3
        with:
          python-version: "3.8"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .
      - name: Test TaskRunner API
        run: |
          python -m tests.github.test_hello_federation --template keras_cnn_mnist --fed_workspace aggregator --col1 col1 --col2 col2  --rounds-to-train 3 --save-model output_model